name: Tag PR

on: 
  pull_request: 
    types: closed
  
jobs:
  tag:
    if: github.event.pull_request.merged && (github.event.pull_request.head.repo == github.event.pull_request.base.repo)
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: create tag git ref
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.git.createRef({
            owner: ${{ github.actor }},
            repo: ${{ github.event.repository }},
            ref: 'refs/tags/pr${{ github.event.number }}',
            sha: ${{ github.event.pull_request.head.sha }}
          }).catch(err => {
            if (err.status !== 409) throw err;
            github.rest.git.updateRef({
              owner: ${{ github.actor }},
              repo: ${{ github.event.repository }},
              ref: 'refs/tags/pr${{ github.event.number }}',
              sha: ${{ github.event.pull_request.head.sha }}
            });
          })
